// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';
import {main} from '../models';

export function ConnectionCreate(arg1:define.Connection):Promise<any>;

export function ConnectionDelete(arg1:string):Promise<any>;

export function ConnectionEdit(arg1:define.Connection):Promise<any>;

export function ConnectionList():Promise<main.M>;

export function CreateKeyValue(arg1:define.CreateKeyValueRequest):Promise<main.M>;

export function DbList(arg1:string):Promise<main.M>;

export function DeleteKeyValue(arg1:define.KeyValueRequest):Promise<main.M>;

export function GetKeyValue(arg1:define.KeyValueRequest):Promise<main.M>;

export function Greet(arg1:string):Promise<string>;

export function KeyList(arg1:define.KeyListRequest):Promise<main.M>;

export function UpdataKeyValue(arg1:define.UpdateKeyValueRequest):Promise<main.M>;
